test_that("gglogger works with ggplot only", {
    p <- ggplot()
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 1)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
})

test_that("gglogger works with ggplot and layers", {
    p <- ggplot() + geom_point()
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 2)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
})

test_that("gglogger works with ggplot and layers and themes", {
    p <- ggplot() + geom_point() + theme_minimal()
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 3)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
    expect_equal(p$logs$logs[[3]]$code, "theme_minimal()")
})

test_that("gglogger works with ggplot and layers and themes and facets", {
    p <- ggplot() + geom_point() + theme_minimal() + facet_wrap(~cyl)
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 4)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
    expect_equal(p$logs$logs[[3]]$code, "theme_minimal()")
    expect_equal(p$logs$logs[[4]]$code, "facet_wrap(~cyl)")
})

test_that("gglogger works with ggplot and layers and themes and facets and scales", {
    p <- ggplot() + geom_point() + theme_minimal() + facet_wrap(~cyl) + scale_color_manual(values = c("red", "blue"))
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 5)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
    expect_equal(p$logs$logs[[3]]$code, "theme_minimal()")
    expect_equal(p$logs$logs[[4]]$code, "facet_wrap(~cyl)")
    expect_equal(p$logs$logs[[5]]$code, "scale_color_manual(values = c(\"red\", \"blue\"))")
})

test_that("gglogger works with ggplot and layers and themes and facets and scales and coordinates", {
    p <- ggplot() + geom_point() + theme_minimal() + facet_wrap(~cyl) + scale_color_manual(values = c("red", "blue")) + coord_flip()
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 6)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
    expect_equal(p$logs$logs[[3]]$code, "theme_minimal()")
    expect_equal(p$logs$logs[[4]]$code, "facet_wrap(~cyl)")
    expect_equal(p$logs$logs[[5]]$code, "scale_color_manual(values = c(\"red\", \"blue\"))")
    expect_equal(p$logs$logs[[6]]$code, "coord_flip()")
})

test_that("gglogger works with ggplot and layers and themes and facets and scales and coordinates and stats", {
    p <- ggplot() + geom_point() + theme_minimal() + facet_wrap(~cyl) + scale_color_manual(values = c("red", "blue")) + coord_flip() + stat_smooth()
    expect_is(p, "gg")
    expect_is(p$logs, "GGLogs")
    expect_equal(length(p$logs$logs), 7)
    expect_equal(p$logs$logs[[1]]$code, "ggplot()")
    expect_equal(p$logs$logs[[2]]$code, "geom_point()")
    expect_equal(p$logs$logs[[3]]$code, "theme_minimal()")
    expect_equal(p$logs$logs[[4]]$code, "facet_wrap(~cyl)")
    expect_equal(p$logs$logs[[5]]$code, "scale_color_manual(values = c(\"red\", \"blue\"))")
    expect_equal(p$logs$logs[[6]]$code, "coord_flip()")
    expect_equal(p$logs$logs[[7]]$code, "stat_smooth()")
})

# test evaluate
test_that("gglogger evaluate works", {
    p <- ggplot(ggplot2::mpg) + geom_point(aes(x = displ, y = hwy))
    q <- p$logs$evaluate()
    expect_is(q, "gg")
    expect_is(q$data, "data.frame")
    expect_equal(nrow(q$data), 234)
    expect_equal(ncol(q$data), 11)
    expect_equal(q$data$displ[1], 1.8)
    expect_equal(q$data$hwy[1], 29)
    expect_is(q$layers[[1]]$geom, "GeomPoint")
    expect_equal(rlang::as_label(q$layers[[1]]$mapping$x), "displ")
    expect_equal(rlang::as_label(q$layers[[1]]$mapping$y), "hwy")
})
