package:
  name: r-gglogger
  version: 0.1.7

source:
  path: ..

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggplot2
    - r-cli
    - r-s7
    - r-rlang

  run:
    - r-base
    - r-ggplot2
    - r-cli
    - r-s7
    - r-rlang

test:
  commands:
    - $R -e "library('gglogger')"

about:
  home: https://github.com/pwwang/gglogger
  license: MIT
  summary: Logs the calls used to create ggplot2 objects.
  license_family: MIT
  license_file: LICENSE.md
