# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: Rscript {0}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - {r: '4.3.3', tf: '2.13'}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        id: setup-r
        with:
          r-version: ${{ matrix.r }}
          Ncpus: '2L'
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: any::devtools, any::pkgdown, any::ggplot2

      - uses: r-lib/actions/check-r-package@v2

      - name: Install gglogger
        run: |
          devtools::install_local(force = TRUE)

      - name: Run tests
        run: |
          devtools::test(stop_on_failure=TRUE)

      - name: Build pkgdown site
        run: |
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
